universe = vanilla
log    =    log/project-chtc_$(Cluster)_$(Process).log
error  =  error/project-chtc_$(Cluster)_$(Process).err
output = out/project-chtc_$(Cluster)_$(Process).out

executable = ./project.sh

arguments = $(file)

should_transfer_files = YES
when_to_transfer_output = ON_EXIT
transfer_input_files = 

request_cpus = 1
request_memory = 1GB
request_disk = 750MB

queue file from file_list_copy