universe = vanilla
log    =    log/project-chtc_$(Cluster)_$(Process).log
error  =  error/project-chtc_$(Cluster)_$(Process).err
output = out/project-chtc_$(Cluster)_$(Process).out

executable = ./project.sh

arguments = $(file)

should_transfer_files = YES
when_to_transfer_output = ON_EXIT
transfer_input_files = packages.tar.gz, http://proxy.chtc.wisc.edu/SQUID/chtc/el8/R413.tar.gz, proj.R

request_cpus = 1
request_memory = 2GB
request_disk = 750MB

queue file from file_list_copy